name: talkjs_flutter_apns_only
description: APNS push notification plugin.
version: 1.0.0
homepage: https://talkjs.com
repository: https://github.com/talkjs/flutter-apns/tree/master/flutter_apns_only

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

platforms:
  ios:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TalkjsFlutterApnsPlugin
