name: talkjs_flutter_apns_only
description: Flutter plugin for Apple Push Notification service (APNs). It enables apps to register and unregister from APNs as well as providing a way to disable the swizzling done by `flutter_messaging`
version: 2.0.0
homepage: https://talkjs.com
repository: https://github.com/talkjs/flutter-apns/tree/master/flutter_apns_only

environment:
  sdk: "^3.10.0"
  flutter: ">=3.38.0"

platforms:
  ios:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TalkjsFlutterApnsPlugin
